### ISSUE TITLE
Fix documentation hosted 404 page 

### ISSUE THREAD

**Issue by ajstewart** [askap-vast/vast-pipeline#542]
404 page in the documentation is not appearing correctly:

![docs-404](https://user-images.githubusercontent.com/3306161/119225356-30031c80-bafb-11eb-8aaa-a48b0ccd6ceb.png)

**Comment by marxide** [comment]
I think it's because we haven't set `site_url` in `mkdocs.yml`. See https://github.com/squidfunk/mkdocs-material/issues/755#issuecomment-380814739.

I've tested setting this locally and it still works. `dev_addr` overrides `site_url` during local tests so there's no issue there. I'll open a PR for this shortly.
